export const PHRASES: readonly string[] = [
  "学べる時こそ最高 ☕",
  "今日も一歩前へ ✨",
  "コツコツが最強の戦略",
  "わからないは成長のサイン",
  "未来の自分が喜ぶ一問を",
  "千里の道も一歩から - 老子",
  "学びて時に之を習う - 孔子",
  "我思う、ゆえに我あり - デカルト",
  "知は力なり - ベーコン",
  "天才とは1%のひらめきと99%の汗 - エジソン",
  "Stay hungry, stay foolish. - Steve Jobs",
  "What we know is a drop, what we don't know is an ocean. - Newton",
  "The expert in anything was once a beginner.",
  "Practice is the best of all instructors. - Publilius Syrus",
  "Try not to become a man of success, but rather try to become a man of value. - Einstein",
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "焦らずゆっくり、着実に",
  "今日の積み重ねが未来をつくる",
  "間違えるほど強くなる",
  "問題を恐れず、楽しもう",
  "小さな進歩こそ大きな勝利",
  "なせばなる、なさねばならぬ何事も - 上杉鷹山",
  "我以外皆我師 - 吉川英治",
  "失敗とは、転ぶことではなく、起き上がらないこと - 孔子",
  "知恵は経験の娘 - レオナルド・ダ・ヴィンチ",
  "Genius is patience. - Buffon",
  "Action is the foundational key to all success. - Picasso",
  "It always seems impossible until it's done. - Mandela",
  "Dream big, start small, act now.",
  "Quality is not an act, it is a habit. - Aristotle",
  "求めよさらば与えられん",
  "継続は力なり",
  "学ぶことに遅すぎることはない",
  "知らないことを知ることが学問の始まり - ソクラテス",
  "汝自身を知れ - ソクラテス",
  "急がず休まず - ゲーテ",
  "怠惰の報酬は失敗である - エマーソン",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "Knowing yourself is the beginning of all wisdom. - Aristotle",
  "He who has a why to live can bear almost any how. - Nietzsche",
  "学問に王道なし - エウクレイデス",
  "問えば一時の恥、問わぬは一生の恥",
  "石の上にも三年",
  "急がば回れ",
  "塵も積もれば山となる",
  "好きこそものの上手なれ",
  "案ずるより産むが易し",
  "明日は明日の風が吹く",
  "雨垂れ石を穿つ",
  "為せば成る",
  "一を聞いて十を知る",
  "Knowledge is power, but enthusiasm pulls the switch. - Steve Droke",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. - Gandhi",
  "If you are working on something that you really care about, you don't have to be pushed. - Steve Jobs",
  "Education is the most powerful weapon which you can use to change the world. - Mandela",
  "深呼吸して、次の一問へ",
  "今日もご機嫌で学ぼう",
  "わかる楽しみを味わって",
  "頭の体操、はじめます",
  "問題は脳の栄養",
  "コーヒーと一緒に過去問を",
  "10 分でいい、続けよう",
  "今日の正解は明日の自信",
  "焦らず、サボらず、しなやかに",
  "君の努力は誰かの希望",
  "がんばり屋さん、今日も来てくれてありがとう",
] as const

export function randomPhrase(): string {
  return PHRASES[Math.floor(Math.random() * PHRASES.length)]
}
